import React from 'react'
import { IoIosArrowBack } from "react-icons/io";

const BlogDetail = () => {
  return (
    <div className='min-h-screen items-center spacing flex flex-col gap-[64px]'>
         <div className='flex gap-4 items-center font-medium text-secondary self-start'>
            <p>BLOG</p>
            <IoIosArrowBack/>
            <p>EXAR</p>
         </div>
         <img className="max-w-[1488px] w-full rounded-md" src="https://via.placeholder.com/1488x653" />
         <div className='flex flex-col 2xl:flex-row 2xl:gap-8 w-full max-w-[1488px] 2xl:justify-between'>
            <div className="w-full md:max-w-[366px] h-28 relative flex-shrink-0">
                    <img className="w-[106px] h-28 left-0 top-0 absolute rounded-md" src="https://via.placeholder.com/106x112" />
                    <div className="w-[223px] left-[143px] top-[48px] absolute text-neutral-800/opacity-80 text-base font-normal font-['Helvetica Neue LT Std']">Lic. en Comunicación. Periodismo tradicional y digital</div>
                    <div className="left-[143px] top-0 absolute text-black text-[32px] font-medium font-['Helvetica Neue LT Std']">Elisabeth Amat</div>
            </div>
            <div className="max-w-[985px] flex-col justify-start items-start gap-16 inline-flex 2xl:py-0 py-[64px]">
                <h2 className='h2-styled'>El Poder del Branding Inmobiliario: Transformando Proyectos en Experiencias Inolvidables</h2>
                <div className="text-neutral-800/opacity-80 text-base font-normal font-['Helvetica Neue LT Std']">Figma ipsum component variant main layer. Plugin ellipse reesizing comment text opacity team. Bullet community pen library community project figjam comment editor selection. Shadow figjam bullet draft library arrange style layout. Strikethrough slice stroke ellipse flows. Asset component shadow stroke community. Content slice scrolling flows rotate figjam. Bullet subtract bold outline object stroke style. Team polygon export ellipse connection arrange figjam. Arrow comment slice prototype ipsum scrolling selection scrolling vector link. Layer shadow vertical subtract frame connection flows ipsum text. Clip flows project font object strikethrough create plugin clip. Outline boolean ipsum group editor library library. Pencil layout team background ipsum pencil. Share background pencil underline figjam style variant list.<br/><br/>Connection share stroke hand subtract device editor invite scrolling. Line fill pen shadow font content bold flows comment. Component pencil rotate line text project bullet. Fill content fill editor vector frame figjam. Link rectangle horizontal vertical figma editor inspect thumbnail. Scale arrow arrow boolean frame polygon object pen clip bold. Line hand main figma draft. Library selection scale draft arrange flows.<br/><br/>Share flows export union bold italic boolean create image create. Reesizing slice figjam horizontal device prototype clip. Component move selection list community flatten figjam. Create arrow ellipse outline blur horizontal clip slice star community. Flows strikethrough subtract comment asset. Asset invite layout vector move figma bullet create. Align follower ipsum duplicate pen content. Plugin distribute frame italic library background vertical follower pencil community. Star scrolling export figjam overflow rotate create. Pencil undo share bullet vertical list inspect.</div>
                <img className="self-stretch h-[480px] rounded-md" src="https://via.placeholder.com/985x480" />
                <div className="text-neutral-800/opacity-80 text-base font-normal font-['Helvetica Neue LT Std']">Fill asset duplicate stroke overflow duplicate comment. Figjam stroke flows image background. Effect reesizing selection edit reesizing flows library inspect. Stroke list bold mask strikethrough flatten boolean style share create. Star star undo pen clip star scale. Component star strikethrough device inspect ipsum scrolling. Prototype follower editor vector scrolling arrange clip prototype ipsum link. Comment invite underline underline select list community team auto horizontal. Arrow rectangle underline overflow project. Invite slice group editor comment overflow horizontal background. Flatten draft variant union image arrange flows list. Vertical image vertical rectangle effect hand slice move hand move.<br/><br/>Group clip hand share figjam link bold edit. Invite mask polygon comment comment. Slice community star opacity outline. Duplicate team figjam distribute community. Rectangle rectangle font invite hand move rectangle italic vector blur. Hand slice group follower italic fill team union main. Duplicate frame auto overflow mask boolean select connection.<br/><br/>Team comment frame layout connection move follower figma flatten. Duplicate figma frame underline share ellipse font italic clip subtract. Device rectangle ipsum ellipse create. Community polygon invite community follower community export ipsum invite. Invite layer editor image selection editor. Italic line outline prototype background draft. Pixel star bullet bold connection selection.<br/><br/>Vertical line align union blur. Asset boolean device arrow effect subtract slice clip comment. Selection follower prototype stroke follower draft follower arrow. Group editor stroke horizontal project asset. Mask frame invite strikethrough component component share clip. Pen underline share polygon project layer scale duplicate. Component outline star auto overflow component. Image blur thumbnail horizontal boolean reesizing hand horizontal. Inspect text create overflow object edit union. Style move team figma fill. Connection selection bold ellipse line variant create asset team. Ipsum group slice vector share selection pencil text. Stroke group figma object main line horizontal. Bullet shadow blur opacity duplicate rotate fill.</div>
            </div>
         </div>
    </div>
  )
}

export default BlogDetail